var lang = {};
lang['english'] = {
    title: "Anonymous Poll",
    browser: "<b>Anonymous Poll</b>",
    user_researsh: "for Users from",
    description: "We give as a thank you to select amongst a several <b>exclusive rewards</b> (each worth over $120 in cash) to the first 20 users who answered the poll's questions. It is very important for us to learn about your opinion concerning the work of the latest version of your web browser.",
    question: "Question",
    yes: "Yes",
    no: "No",
    hz: "I don't know",
    question1: "Do you use this browser as the default one?",
    question2: "What do you like most in this browser?",
    q2ans1: "Interface",
    q2ans2: "Safety and security",
    q2ans3: "High speed",
    question3: "Where are you using this browser right now?",
    q3ans1: "At home",
    q3ans2: "At work",
    q3ans3: "Other",
    question4: "What is the degree of your satisfaction with the latest updates of this browser?",
    q4ans1: "Satisfied",
    q4ans2: "Dissatisfied",
    q4ans3: "Completely satisfied",
    loading1: "<b>Thank you for your participation!</b>",
    loading2: "<b>Now you will be redirected to the rewards page</b>",
    loading3: "<b>Checking answers</b>",
    loading4: "<b>Loading available rewards</b>",
    loading5: "Checking IP",
    thank_you: "<b>Thank you for expending your time in taking this user satisfaction survey!</b>",
    remaining: "In stock!",
    claim: "Get My Reward!",
    notav: "Out of stock",
    dayarray: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    montharray: ["january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december"],
	alert: "Dear User of the Browser. Please answer a few questions and you can select (1) from several <b>exclusive rewards</b> each worth over $120 in cash!",
    onbeforeunload: "You have a chance to get a free Apple iPhone 7. Do you really want to stop the survey?",
    regular: "Regular Price:",
    time: "Limited time: ",
    reward: "$0.00",
    con: "Congratulations!",
    next: "Next question"
};

lang['thai'] = {
    title: "Anonymous Poll",
    browser: "<b>Anonymous Poll</b>",
    user_researsh: "for Users from",
    description: "We give as a thank you to select amongst a several <b>exclusive rewards</b> (each worth over $120 in cash) to the first 20 users who answered the poll's questions. It is very important for us to learn about your opinion concerning the work of the latest version of your web browser.",
    question: "Question",
    yes: "Yes",
    no: "No",
    hz: "I don't know",
    question1: "Do you use this browser as the default one?",
    question2: "What do you like most in this browser?",
    q2ans1: "Interface",
    q2ans2: "Safety and security",
    q2ans3: "High speed",
    question3: "Where are you using this browser right now?",
    q3ans1: "At home",
    q3ans2: "At work",
    q3ans3: "Other",
    question4: "What is the degree of your satisfaction with the latest updates of this browser?",
    q4ans1: "Satisfied",
    q4ans2: "Dissatisfied",
    q4ans3: "Completely satisfied",
    loading1: "<b>Thank you for your participation!</b>",
    loading2: "<b>Now you will be redirected to the rewards page</b>",
    loading3: "<b>Checking answers</b>",
    loading4: "<b>Loading available rewards</b>",
    loading5: "Checking IP",
    thank_you: "<b>Thank you for expending your time in taking this user satisfaction survey!</b>",
    remaining: "In stock!",
    claim: "Get it 50% OFF!",
    notav: "Out of stock",
    dayarray: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    montharray: ["january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december"],
	alert: "Dear User of the Browser. Please answer a few questions and you can select (1) from several <b>exclusive rewards</b> each worth over $120 in cash!",
    onbeforeunload: "You have a chance to get a free Apple iPhone 7. Do you really want to stop the survey?",
    regular: "Regular Price:",
    time: "Limited time: ",
    reward: "Reward",
    con: "Congratulations!",
    next: "Next question"
};


lang['russia'] = {
    title: "Анонимный опрос пользователей",
    browser: "Анонимный опрос пользователей браузера",
    user_researsh: "Опрос пользователей из",
    description: "Мы дарим Apple iPhone 7 первым 100 пользователям ответившим на вопросы. Нам очень важно узнать Ваше мнение о работе последней версии браузера.",
    question: "Вопрос",
    yes: "Да",
    no: "Нет",
    hz: "Не знаю",
    question1: "Вы используете наш браузер, как браузер по умолчанию?",
    question2: "Что вам больше всего нравится в нашем браузере?",
    q2ans1: "Интерфейс",
    q2ans2: "Надежность и безопасность",
    q2ans3: "Высокая скорость",
    question3: "Где вы используете браузер прямо сейчас?",
    q3ans1: "Дома",
    q3ans2: "На работе",
    q3ans3: "Другое",
    question4: "Насколько Вы удовлетворены работой последних обновлений браузера?",
    q4ans1: "Удовлетворен",
    q4ans2: "Неудовлетворен",
    q4ans3: "Крайне удовлетворен",
    loading1: "Мы благодарны Вам за Ваше участие!",
    loading2: "Сейчас мы перенаправим Вас к базе призов.",
    loading3: "Проверка ответов",
    loading4: "Проверка IP адреса",
    loading5: "Загружаем оставшиеся призы",
    thank_you: "Благодарим за время потраченное на опрос. Выберите один из доступных подарков.",
    remaining: "Осталось",
    claim: "Получить",
    notav: "Недоступно",
    dayarray: ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"],
    montharray: ["января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря"],
    alert: "Уважаемый пользователь браузера. Ответьте на несколько вопросов и получите БЕСПЛАТНО Apple iPhone 7!",
    onbeforeunload: "У Вас есть шанс БЕСПЛАТНО получить Apple iPhone 7. Вы уверены что хотите завершить опрос?",
    regular: "Обычная цена",
    time: "Текущий статус: ",
    reward: "Приз",
    con: "Поздравляем!",
    next: "Далее"

};


lang['france'] = {
    title: "Enquête anonyme",
    browser: "Enquête anonyme",
    user_researsh: "Recherche d’utilisateur à",
    description: "Nous offrons le nouvel Apple iPhone 7 aux 100 premiers utilisateurs à répondre aux questions de l'enquête. Votre avis concernant la version la plus récente de votre navigateur Internet compte énormément pour nous.",
    question: "Question",
    yes: "Oui",
    no: "Non",
    hz: "Je ne sais pas",
    question1: "Notre navigateur est-il votre navigateur par défaut?",
    question2: "Qu'est-ce qui vous plaît le plus dans notre navigateur?",
    q2ans1: "Son interface",
    q2ans2: "Sa sécurité/sûreté",
    q2ans3: "Sa grande vitesse",
    question3: "Où utilisez-vous votre navigateur en ce moment même?",
    q3ans1: "À la maison",
    q3ans2: "Au travail",
    q3ans3: "Autre",
    question4: "Quel est votre degré de satisfaction concernant les mises à jour les plus récentes de votre navigateur?",
    q4ans1: "Satisfait(e)",
    q4ans2: "Non satisfait(e)",
    q4ans3: "Complètement satisfait(e)",
    loading1: "Merci pour votre participation!",
    loading2: "Vous allez être redirigé(e) vers notre base de prix.",
    loading3: "Vérification des réponses",
    loading4: "Vérification des IP",
    loading5: "Chargement des prix disponibles",
    thank_you: "Merci d'avoir consacré du temps à répondre à notre enquête de satisfaction.",
    remaining: "En stock",
    claim: "Recevoir",
    notav: "Épuisé",
    dayarray: ["Sunday", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Saturday"],
    montharray: ["Janvier", "Février", "Mars", "Avril", "Peut", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
    alert: "Cher/chère utilisateur/trice du navigateur. Répondez à quelques questions et tentez de remporter gratuitement un Apple iPhone 7!",
    onbeforeunload: "Vous avez une chance de remporter gratuitement un Apple iPhone 7. Souhaitez-vous vraiment interrompre l'enquête?",
    regular: "Prix régulier:",
    time: "Valeur actuelle: ",
    reward: "La prime",
    con: "Félicitations!",
    next: "Question suivante"
};



lang['germany'] = {
    title: "Anonyme Umfrage",
    browser: "Anonyme Umfrage",
    user_researsh: "afür Nutzer aus",
    description: "Wir geben den ersten 100 Nutzern, die die Umfrage ausfüllen das neue kostenlose Apple iPhone 7. Für uns ist es sehr wichtig, dass wir mehr über deine Einstellung zur aktuellen Version deines Internetbrowsers erfahren.",
    question: "Frage",
    yes: "Ja",
    no: "Nein",
    hz: "Ich weiß nicht",
    question1: "Verwendest du unseren Browser als Standardbrowser?",
    question2: "Was gefällt dir an unserem Browser am besten?",
    q2ans1: "Die Benutzeroberfläche",
    q2ans2: "Die Sicherheit",
    q2ans3: "Hohe Geschwindigkeit",
    question3: "Wo benutzt du deinen Browser gerade?",
    q3ans1: "Zuhause",
    q3ans2: "Bei der Arbeit",
    q3ans3: "Anderswo",
    question4: "Wie zufrieden bist du mit den neusten Updates deines Browsers?",
    q4ans1: "Zufrieden",
    q4ans2: "Unzufrieden",
    q4ans3: "Vollständig zufrieden",
    loading1: "Vielen Dank, dass du teilgenommen hast!",
    loading2: "Du wirst jetzt zur Preisseite weitergeleitet",
    loading3: "Antworten werden überprüft",
    loading4: "IP werden überprüft",
    loading5: "Verfügbare Preise werden geladen",
    thank_you: "Vielen Dank, dass du dir die Zeit genommen hast, an unserer Nutzerzufriedenheitsumfrage ",
    remaining: "Auf Lager",
    claim: "Erhalten",
    notav: "Nicht auf Lager",
    dayarray: ["Sunday", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Saturday"],
    montharray: ["Januar", "Februar", "März", "April", "Mai", "June", "Juli", "August", "September", "October", "November", "December"],
    alert: "Lieber Nutzer des Browsers. Bitte beantworte ein paar Fragen und erhalte eine Chance, ein kostenloses Apple iPhone 7 zu gewinnen!",
    onbeforeunload: "Du hast die Gelegenheit, ein kostenloses Apple iPhone 7 zu erhalten. Möchtest du die Umfrage wirklich abbrechen?",
    regular: "Regulärer Preis:",
    time: "Aktueller Status: ",
    reward: "Geschenk",
    con: "Herzlichen Glückwunsch!",
    next: "Nächste Frage"
};



lang['portugal'] = {
    title: "Inquérito anónimo",
    browser: "Inquérito anónimo",
    user_researsh: "aos utilizadores da",
    description: "Vamos oferecer o novo Apple iPhone 7 gratuitamente aos primeiros 100 utilizadores que responderem às questões do inquérito. É muito importante para nós saber a sua opinião sobre o funcionamento da versão mais recente do seu browser Web.",
    question: "Questão",
    yes: "Sim",
    no: "Não",
    hz: "Não sei",
    question1: "Utiliza o nosso browser como browser predefinido?",
    question2: "Do que gosta mais no nosso browser?",
    q2ans1: "Interface",
    q2ans2: "Proteção e segurança",
    q2ans3: "Alta velocidade",
    question3: "Onde é que está a utilizar o seu browser neste momento?",
    q3ans1: "Em casa",
    q3ans2: "No trabalho",
    q3ans3: "Outro",
    question4: "Qual é o seu nível de satisfação com as últimas atualizações do seu browser?",
    q4ans1: "Satisfeito",
    q4ans2: "Insatisfeito",
    q4ans3: "Totalmente satisfeito",
    loading1: "Obrigado pela sua participação!",
    loading2: "Agora vai ser redirecionado para a base do prémio",
    loading3: "A verificar as respostas",
    loading4: "A verificar as respostas IP",
    loading5: "A carregar os prémios disponíveis",
    thank_you: "Obrigado por ter despendido do seu tempo no nosso inquérito de satisfação ao utilizador.",
    remaining: "Em stock",
    claim: "Receba",
    notav: "Sem stock",
    dayarray: ["Domingo", "Segunda-feira", "terça-feira", "Wednesday", "Quinta-feira", "Friday", "Saturday"],
    montharray: ["Janeiro", "Fevereiro", "March", "Abril", "pode", "June", "Julho", "August", "September", "Outubro", "November", "Dezembro"],
    alert: "Caro utilizador do browser. Responda a algumas questões e tenha a oportunidade de ganhar um Apple iPhone 7 grátis!",
    onbeforeunload: "Tem a oportunidade de ter um Apple iPhone 7 grátis. Quer mesmo interromper o questionário?",
    regular: "Preço normal:",
    time: "Estado actual: ",
    reward: "Prêmio",
    con: "Parabéns!",
    next: "Próxima questão"
};



lang['italy'] = {
    title: "Sondaggio anonimo",
    browser: "Sondaggio anonimo",
    user_researsh: "per utenti dalla",
    description: "Regaliamo il nuovo Apple iPhone 7 ai primi 100 utenti che rispondono alle domande del sondaggio. È molto importante per noi sapere cosa ne pensi dell'ultima versione del tuo browser web.",
    question: "Domanda",
    yes: "Sì",
    no: "No",
    hz: "Non so",
    question1: "Utilizzi il nostro browser come predefinito?",
    question2: "Che cosa ti piace di più del nostro browser?",
    q2ans1: "Interfaccia",
    q2ans2: "Protezione e sicurezza",
    q2ans3: "Alta velocità",
    question3: "Dove stai utilizzando il tuo browser adesso?",
    q3ans1: "A casa",
    q3ans2: "Al lavoro",
    q3ans3: "Altro",
    question4: "Qual è il tuo grado di soddisfazione rispetto agli ultimi aggiornamenti del tuo browser?",
    q4ans1: "Soddisfatto",
    q4ans2: "Non soddisfatto",
    q4ans3: "Completamente soddisfatto",
    loading1: "Grazie per aver partecipato!",
    loading2: "Ora verrai reindirizzato ai premi.",
    loading3: "Verifica delle risposte",
    loading4: "Verifica delle IP",
    loading5: "Caricamento dei premi disponibili",
    thank_you: "Grazie per aver dedicato del tempo al nostro sondaggio di soddisfazione utente.",
    remaining: "In stock",
    claim: "Ricevi",
    notav: "Stock esaurito",
    dayarray: ["Domenica", "Lunedi", "Martedì", "Mercoledì", "Giovedi", "Venerdì", "Sabato"],
    montharray: ["Gennaio", "Febbraio", "Marzo", "Aprile", "Può", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "December"],
    alert: "Gentile utente del browser. Rispondi ad alcune domande e avrai la possibilità di vincere un Apple iPhone 7 gratis!",
    onbeforeunload: "Hai la possibilità di ottenere un Apple iPhone 7 gratis. Vuoi comunque interrompere il sondaggio?",
    regular: "Prezzo normale:",
    time: "Stato attuale: ",
    reward: "Premio",
    con: "Complimenti!",
    next: "Prossima domanda"
};





lang['netherlands'] = {
    title: "Anonieme poll",
    browser: "Anonieme poll",
    user_researsh: "voor gebruikers uit",
    description: "We stellen de nieuwe Apple iPhone 7 gratis ter beschikking aan de eerste 100 gebruikers die de vragen uit de poll beantwoorden. We willen graag weten wat u vindt van de nieuwste versie van uw webbrowser.",
    question: "Vraag",
    yes: "Ja",
    no: "Nee",
    hz: "Weet ik niet",
    question1: "Gebruikt u onze browser als standaardbrowser?",
    question2: "Wat vindt u het fijnst aan onze browser?",
    q2ans1: "Interface",
    q2ans2: "Veiligheid en beveiliging",
    q2ans3: "Hoge snelheid",
    question3: "Waar gebruikt u uw browser op dit moment?",
    q3ans1: "Thuis",
    q3ans2: "Op het werk",
    q3ans3: "Elders",
    question4: "Hoe tevreden bent u met de nieuwste updates van uw browser?",
    q4ans1: "Tevreden",
    q4ans2: "Ontevreden",
    q4ans3: "Zeer tevreden",
    loading1: "Bedankt voor uw deelname!",
    loading2: "U wordt nu naar de prijzenpagina geleid",
    loading3: "Antwoorden controleren",
    loading4: "IP controleren",
    loading5: "Beschikbare prijzen laden",
    thank_you: "Bedankt voor uw tijd en uw deelname aan ons tevredenheidsonderzoek.",
    remaining: "Op voorraad",
    claim: "Ontvang",
    notav: "Niet op voorraad",
    dayarray: ["Zondag", "Monday", "dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag"],
    montharray: ["Januari", "Februari", "Mars", "April", "kan", "Juni", "Juli", "August", "September", "Oktober", "November", "December"],
    alert: "Beste gebruiker van de browser. Beantwoord een paar vragen en maak kans op een gratis Apple iPhone 7!",
    onbeforeunload: "U maakt kans op een gratis Apple iPhone 7. Wilt u echt stoppen met de vragenlijst?",
    regular: "Normale prijs:",
    time: "Huidige status: ",
    reward: "Prijs",
    con: "Gefeliciteerd!",
    next: "Volgende vraag"
};




lang['spain'] = {
    title: "Encuesta anónima",
    browser: "Encuesta anónima",
    user_researsh: "para usuarios de",
    description: "Entregaremos el nuevo Apple iPhone 7 gratis a los primeros 100 usuarios que respondan las preguntas de la encuesta. Para nosotros es muy importante saber vuestra postura en cuanto el funcionamiento de la versión más reciente de vuestro navegador web.",
    question: "Pregunta",
    yes: "Sí",
    no: "No",
    hz: "No lo sé",
    question1: "¿Usas nuestro navegador como el predeterminado?",
    question2: "¿Qué te gusta más de nuestro navegador?",
    q2ans1: "La interfaz",
    q2ans2: "La seguridad",
    q2ans3: "La velocidad",
    question3: "¿Dónde usas tu navegador en este momento?",
    q3ans1: "En casa",
    q3ans2: "En el trabajo",
    q3ans3: "Otro",
    question4: "¿Cuál es tu grado de satisfacción con las versiones más recientes de tu navegador?",
    q4ans1: "Satisfecho",
    q4ans2: "Insatisfecho",
    q4ans3: "Totalmente satisfecho",
    loading1: "¡Gracias por tu participación!",
    loading2: "Ahora te dirigiremos a la base de premios.",
    loading3: "Comprobando respuestas",
    loading4: "Comprobando IP",
    loading5: "Cargando premios disponibles",
    thank_you: "Gracias por dedicar unos instantes a realizar nuestra encuesta de satisfacción de usuario.",
    remaining: "En existencias",
    claim: "Recibir",
    notav: "Sin existencias",
    dayarray: ["Sunday", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
    montharray: ["Enero", "Febrero", "Marcha", "Abril", "puede", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
    alert: "Estimado usuario del navegador. Por favor, responde unas preguntas para tener la posibilidad de ganar un Apple iPhone 7 gratis.",
    onbeforeunload: "Tienes la oportunidad de obtener un Apple iPhone 7 gratis. ¿Seguro que quieres salir de la encuesta?",
    regular: "Precio regular:",
    time: "Estado actual: ",
    reward: "Premio",
    con: "Felicitaciones!",
    next: "Próxima pregunta"
};
